=== Dheaamelia/latihanpraktikumdantugas3/travel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsixml"/>
    <xs:element name="travel">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="biaya"/>
                <xs:element ref="email"/>
                <xs:element ref="jeniskelamin"/>
                <xs:element ref="kota_awal"/>
                <xs:element ref="kota_tujuan"/>
                <xs:element ref="kursi"/>
                <xs:element ref="nama"/>
                <xs:element ref="nama_bus"/>
                <xs:element ref="no_ktp"/>
                <xs:element ref="no_kursi"/>
                <xs:element ref="tgl_berangkat"/>
            </xs:choice>
            <xs:attribute name="Data" use="required" type="xs:NCName"/>
            <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="biaya" type="xs:integer"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="jeniskelamin" type="xs:NCName"/>
    <xs:element name="kota_awal" type="xs:NCName"/>
    <xs:element name="kota_tujuan" type="xs:NCName"/>
    <xs:element name="kursi">
        <xs:complexType>
            <xs:attribute name="nomor" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama" type="xs:string"/>
    <xs:element name="nama_bus" type="xs:NCName"/>
    <xs:element name="no_ktp" type="xs:integer"/>
    <xs:element name="no_kursi" type="xs:integer"/>
    <xs:element name="tgl_berangkat" type="xs:string"/>
</xs:schema>

=== Dheaamelia/latihanpraktikumdantugas3/Travel.xml
<?xml version="1.0" encoding="UTF-8"?>
<travel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="travel.xsd">
	
	<nama>Rudi Irmawan</nama>
	<no_ktp>0000123456677</no_ktp>
	<jeniskelamin>Lak-laki</jeniskelamin>
	<tgl_berangkat>12 April 2017</tgl_berangkat>
	<nama_bus>primajasa</nama_bus>
	<kota_awal>bandung</kota_awal>
	<kota_tujuan>Jakarta</kota_tujuan>
	<biaya>95000</biaya>
	<email>rudiirawan56@gmail.com</email>
	<kursi nomor="13">
	</kursi>
	
	<nama>Meli Rosmalina</nama>
	<no_ktp>0000126538747</no_ktp>
	<jeniskelamin>Perempuan</jeniskelamin>
	<tgl_berangkat>14 April 2017</tgl_berangkat>
	<nama_bus>primajasa</nama_bus>
	<kota_awal>bandung</kota_awal>
	<kota_tujuan>Surabaya</kota_tujuan>
	<biaya>100000</biaya>
	<email>rosmalina.meli@gmail.com</email>
	<kursi nomor="12">
	</kursi>
	
	
	<nama>Claudia Santika</nama>
	<no_ktp>00001263546318</no_ktp>
	<jeniskelamin>Perempuan</jeniskelamin>
	<tgl_berangkat>14 April 2017</tgl_berangkat>
	<nama_bus>widia</nama_bus>
	<kota_awal>jakarta</kota_awal>
	<kota_tujuan>Yogyakarta</kota_tujuan>
	<biaya>120000</biaya>
	<email>csantika@gmail.com</email>
	<kursi nomor="07">
	</kursi>
	
	
	<nama>Gustian Maulida</nama>
	<no_ktp>0000126457214689</no_ktp>
	<jeniskelamin>Laki-laki</jeniskelamin>
	<tgl_berangkat>15 April 2017</tgl_berangkat>
	<nama_bus>primajasa</nama_bus>
	<kota_awal>Jakarta</kota_awal>
	<kota_tujuan>Subang</kota_tujuan>
	<biaya>85000</biaya>
	<email>gustianmaulida@gmail.com</email>
	<kursi nomor="10">
	</kursi>
	
	<nama>Anggun Permatasari</nama>
	<no_ktp>000012684591384</no_ktp>
	<jeniskelamin>Perempuan</jeniskelamin>
	<tgl_berangkat>14 April 2017</tgl_berangkat>
	<nama_bus>primajasa</nama_bus>
	<kota_awal>Bandung</kota_awal>
	<kota_tujuan>Semarang</kota_tujuan>
	<no_kursi>13</no_kursi>
	<biaya>150000</biaya>
	<email>anggunpermatasari@gmail.com</email>
	<kursi nomor="17">
	</kursi>
	
</travel>
